apiVersion: v1
kind: Pod
metadata:
  name: pvc-demo
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: my-persistent-storage
      mountPath: /data
  volumes:
  - name: my-persistent-storage
    persistentVolumeClaim:
      claimName: demo-pvc
