apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: YWRtaW4=
  mongo-root-password: YWRtaW4=
---
apiVersion: v1
kind: Secret
metadata:
  name: express-secret
type: Opaque
data:
  mongo-basic-username: dXNlcg==
  mongo-basic-password: dXNlcg==
